# Generated by Django 3.1.3 on 2020-11-28 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('title', models.CharField(max_length=50, unique=True)),
                ('id', models.CharField(default=1, max_length=25, primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=25)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
