# Generated by Django 3.1.3 on 2020-12-06 00:49

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201206_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'date_created']),
        ),
    ]
