# Generated by Django 3.1.3 on 2020-12-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20201206_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='slug',
        ),
    ]
