# Generated by Django 3.1.3 on 2020-12-06 02:37

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20201206_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'date_created'], unique=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'date_created'], unique=True),
        ),
    ]
