# Generated by Django 3.1.3 on 2020-12-06 03:29

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20201206_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['date_created'], unique=True),
        ),
    ]
